#! /bin/sh

name=kernel
version=0.0git
revision=2
source_dir="kernel"
source_allow_network="yes"
hostdeps="gcc"
imagedeps="nasm"
deps="core-libs"

prepare() {
    ./get-deps
}

build() {
    cp -rpf "${source_dir}"/. ./

    make -j${parallelism} \
        CFLAGS="$KERNEL_CFLAGS -O2 -pipe" \
        TOOLCHAIN=${OS_TRIPLET}
}

package() {
    make install PREFIX="${prefix}" DESTDIR="${dest_dir}"

    post_package_strip
}
