#! /bin/sh

set -ex

srcdir="$(dirname "$0")"
test -z "$srcdir" && srcdir=.

cd "$srcdir"

clone_repo_commit() {
    if test -d "$2/.git"; then
        git -C "$2" reset --hard
        git -C "$2" clean -fd
        if ! git -C "$2" -c advice.detachedHead=false checkout $3; then
            rm -rf "$2"
        fi
    else
        if test -d "$2"; then
            set +x
            echo "error: '$2' is not a Git repository" 1>&2
            exit 1
        fi
    fi
    if ! test -d "$2"; then
        git clone $1 "$2"
        if ! git -C "$2" -c advice.detachedHead=false checkout $3; then
            rm -rf "$2"
            exit 1
        fi
    fi
}

clone_repo_commit \
    https://github.com/osdev0/freestnd-c-hdrs-0bsd.git \
    freestnd-c-hdrs \
    5e4e9e70278fe89ea328d359a58aff4f4a94b165

clone_repo_commit \
    https://github.com/osdev0/cc-runtime.git \
    cc-runtime \
    dae79833b57a01b9fd3e359ee31def69f5ae899b

clone_repo_commit \
    https://github.com/limine-bootloader/limine-protocol.git \
    limine-protocol \
    fedf97facd1c473ee8720f8dfd5a71d03490d928

clone_repo_commit \
    https://github.com/mintsuki/flanterm.git \
    flanterm \
    fa3ee697b4a9d0a506e5249a791ae2f830a0bf4c

clone_repo_commit \
    https://github.com/uACPI/uACPI.git \
    uacpi \
    022bc38ee675da1c63e6a6567e510cf58b3d2f7e

clone_repo_commit \
    https://github.com/charlesnicholson/nanoprintf.git \
    nanoprintf \
    9c25f798f88302d768a016744d0ba1730f6548cc

rm -rf mlibc-headers
rm -rf mlibc/build
clone_repo_commit \
    https://github.com/managarm/mlibc.git \
    mlibc \
    348d5a5bb6049e6505066f2e28cd223b35fb612a
# XXX remove once upstreamed
( cd mlibc && patch -p1 < ../../patches/mlibc/jinx-working-patch.patch )
mkdir -p mlibc/build
cd mlibc/build
meson setup \
    --cross-file ../../cross_file.txt \
    --prefix=/ \
    -Dheaders_only=true \
    ..
ninja
mkdir ../../mlibc-headers
DESTDIR="$(cd ../../mlibc-headers && pwd -P)" ninja install
cd ../..

set +x

printf "\nDependencies obtained successfully!\n"
